### ISSUE TITLE
大佬，求个问题

### ISSUE THREAD

**Issue by AyanamiRito** [MidCheck/novelsCraw#1]
大佬为何使用pycharm运行，直接显示Process finished with exit code 0，未有结果

**Comment by MidCheck** [comment]
"Process finished with exit code 0"这句话是说程序正常退出了，看下运行的时候是不是没有传参数或者出现异常了，能否贴下运行截图呢

**Comment by AyanamiRito** [comment]
![{_HTI{}6QRIN I~UKB3QQDU](https://github.com/MidCheck/novelsCraw/assets/98450031/5b4a8196-5663-4760-9a34-7cd479a5607b)
感谢大佬回复

**Comment by MidCheck** [comment]
没有输出内容是由于正则表达式没有匹配到小说目录链接导致，已经在代码里增加了[报错信息](https://github.com/MidCheck/novelsCraw/blob/bfa748b55d11197efbcd497d2071fb3fd87a8264/novel_scraw.py#L99)

看到你的环境是Python3.9，测试了下Python3.9，使用requests_html库获取这个小说网站请求时，没有正确处理Javascript，[返回的内容](https://github.com/MidCheck/novelsCraw/blob/bfa748b55d11197efbcd497d2071fb3fd87a8264/novel_scraw.py#L78)不正确，使用Python3.10及以上版本的Python就好了

**Comment by AyanamiRito** [comment]
问题解决了 ，感谢大佬
